# Hexapod.toml
user = "dietpi"
host = "hexssh.prime-empire.eu"
host_local = "hexapod.local"
remote_path = "/home/dietpi/hexapod-devkit/remoterun/"
target = "aarch64-unknown-linux-gnu"
builder = "cross"