# PC BUILDS
[tasks.pccheck]
command = "cargo"
args = ["check", "--features", "dummy"]
workspace = false

[tasks.pcbuild]
command = "cargo"
args = ["build", "--features", "dummy"]
workspace = false

[tasks.pcbuildrelease]
command = "cargo"
args = ["build", "--features", "dummy", "--release"]
workspace = false

[tasks.pcrun]
command = "cargo"
args = ["run", "--release", "--features", "dummy"]
workspace = false

[tasks.pcrunrelease]
command = "cargo"
args = ["run", "--features", "dummy", "--release"]
workspace = false

[tasks.pcrunsim]
command = "cargo"
args = ["run", "-p", "hexapod_sim"]
workspace = false

# RASPBERRY PI BUILDS
[tasks.picheck]
command = "cross"
args = ["check", "--target", "aarch64-unknown-linux-gnu", "--features", "real"]
workspace = false

[tasks.pibuild]
command = "cross"
args = ["build", "--target", "aarch64-unknown-linux-gnu", "--features", "real"]
workspace = false

[tasks.pibuildrelease]
command = "cross"
args = ["build", "--target", "aarch64-unknown-linux-gnu", "--features", "real", "--release"]
workspace = false

[tasks.pirunremote]
workspace = false

[tasks.pirunremote.linux]
command = "cargo"
args = ["hexapod-devkit", "remoterun", "--local"]

[tasks.pirunremote.windows]
command = "powershell"
args = ["-ExecutionPolicy", "Bypass", "-File", "remoterun.ps1", "-r"]

# Adam nix shell wrappers for Pi builds
[tasks.nixpibuildrelease]
command = "nix-shell"
args = ["-p", "cargo-cross", "--run", "cargo make pibuildrelease"]
workspace = false

[tasks.nixpirunremote]
command = "nix-shell"
args = ["-p", "cargo-cross", "--run", "cargo make pirunremote"]
workspace = false
